### ISSUE TITLE
Machacado del grupo 11 en el Hands-on

### ISSUE THREAD

**Issue by PabloFdez** [FacultadInformatica-LinkedData/Curso2016-2017#392]
Subimos los ficheros del Hands-on en el directorio Group-11, pero otro grupo también puso ese nombre y los ficheros se han machacado. 
¿Subimos los ficheros en otro grupo o nos quedamos en el 11?

**Comment by rgcmme** [comment]
Si los que hay ahora en el repositorio son los del otro grupo, por favor, subir los vuestros en un nuevo directorio.

**Comment by labiagajaime** [comment]
Hi,
There is a problem on HandsOn/Group11/ about duplicated files (with same name). Windows can not store files with the same file. So, after do a fetch request, Windows don't save both files. Because of this my mates and I can not commit anything.

$ git status
On branch master
Your branch is ahead of 'origin/master' by 318 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
    modified:   HandsOn/Group11/Members.html
    modified:   HandsOn/Group11/Requirements/dataSetRequirements.html
```

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by rgcmme** [comment]
Hi,
Two groups had submitted into the same directory and using file names only changing in the first letter (capital and non-capital), which gives problems in some operating systems.
I have cleaned up the directory; however, check that everything is right before updating your local copy.

**Comment by labiagajaime** [comment]
How can I get the last changes?. I can not get out of my status of my previous comment

**Comment by rgcmme** [comment]
You have to fetch the changes made from others, update your working copy and so on: https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git:-Fork,-Branching,-Commits,-and-Pull-Request

**Comment by labiagajaime** [comment]
I don't understand. Need help

**Comment by labiagajaime** [comment]
I deleted my repo and cloned the main repo

**Comment by rgcmme** [comment]
Is it working now?
